import React, { useState, useMemo } from 'react';
import { AlertCircle, AlertTriangle, ShieldCheck, CheckCircle2, Search, Filter, ArrowRight } from 'lucide-react';
import { useInvestigation } from '../../context/InvestigationContext';
import AddressBadge from '../common/AddressBadge';
import SeverityBadge from '../common/SeverityBadge';
import EmptyState from '../common/EmptyState';
import clsx from 'clsx';

export default function AlertsView() {
  const {
    traceData,
    selectAddress,
    selectTransaction,
    alertStatuses,
    updateAlertStatus,
  } = useInvestigation();

  const { alerts = [], chain = 'ethereum' } = traceData || {};

  const [severityFilter, setSeverityFilter] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');

  const enrichedAlerts = useMemo(() => {
    return alerts.map((alert, idx) => {
      const alertId = `ALT-${(idx + 1).toString().padStart(4, '0')}`;
      const status = alertStatuses[alertId] || 'new';
      return {
        ...alert,
        alertId,
        status,
      };
    });
  }, [alerts, alertStatuses]);

  const filteredAlerts = useMemo(() => {
    return enrichedAlerts.filter((a) => {
      if (severityFilter !== 'all' && (a.severity || 'medium').toLowerCase() !== severityFilter) {
        return false;
      }
      if (searchTerm) {
        const q = searchTerm.toLowerCase();
        const typeMatch = (a.type || '').toLowerCase().includes(q);
        const addrMatch = (a.address || '').toLowerCase().includes(q);
        const entityMatch = (a.entity || '').toLowerCase().includes(q);
        if (!typeMatch && !addrMatch && !entityMatch) return false;
      }
      return true;
    });
  }, [enrichedAlerts, severityFilter, searchTerm]);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* ── Top Header ───────────────────────────────────────────────────── */}
      <div className="cyber-panel p-6 border-red-500/20 bg-gradient-to-r from-panel to-red-950/[0.08]">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="text-xs uppercase font-mono px-2 py-0.5 rounded bg-red-500/10 text-red-400 border border-red-500/30">
                Triage Console
              </span>
              <span className="text-xs font-mono text-gray-400">
                Rule-Linked Alerts
              </span>
            </div>
            <h2 className="text-lg font-bold text-gray-100">Investigative Alert Stream</h2>
            <p className="text-xs text-gray-400 mt-1 max-w-2xl">
              Signals generated by the backend alert engine triggered by high-priority attribution tiers, observed typologies, and institutional VASP hops.
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs font-mono text-red-400 bg-black/40 px-3 py-1.5 rounded border border-panel-border">
              {alerts.length} Active Alert{alerts.length !== 1 ? 's' : ''}
            </span>
          </div>
        </div>

        <div className="mt-4 pt-3 border-t border-panel-border/50 text-[11px] text-gray-400 italic">
          Alert review statuses (Reviewed, Escalated, Dismissed) are maintained during your active investigation session.
        </div>
      </div>

      {/* ── Filters Bar ──────────────────────────────────────────────────── */}
      <div className="cyber-panel p-4 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
        <div className="relative w-full sm:w-72">
          <Search className="w-4 h-4 absolute left-3 top-2.5 text-gray-500" />
          <input
            type="text"
            placeholder="Filter by type, address, entity..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="cyber-input w-full pl-9 text-xs"
          />
        </div>

        <div className="flex items-center gap-2 self-end sm:self-auto">
          <label className="text-gray-400 shrink-0">Severity:</label>
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="cyber-input text-xs bg-background"
          >
            <option value="all">All Severities</option>
            <option value="high">High Only</option>
            <option value="medium">Medium Only</option>
            <option value="informational">Informational / Low</option>
          </select>
        </div>
      </div>

      {/* ── Alert List ───────────────────────────────────────────────────── */}
      {filteredAlerts.length === 0 ? (
        <EmptyState
          title="No Alerts Match Filters"
          subtitle="No alerts match the selected severity or search criteria."
          icon={ShieldCheck}
          type="neutral"
        />
      ) : (
        <div className="space-y-3">
          {filteredAlerts.map((alert) => {
            const isHigh = alert.severity === 'high';
            const alertTitle = (alert.type || 'Alert')
              .replace(/_/g, ' ')
              .replace(/\b\w/g, (l) => l.toUpperCase());

            return (
              <div
                key={alert.alertId}
                className={clsx(
                  'cyber-panel p-5 space-y-3 transition-colors border',
                  isHigh ? 'border-red-500/40 bg-red-950/[0.04]' : 'border-panel-border bg-black/20'
                )}
              >
                {/* Alert Top Row */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-panel-border/50 pb-2.5">
                  <div className="flex items-center gap-2.5">
                    <span className="font-mono text-xs font-bold text-gray-400">
                      {alert.alertId}
                    </span>
                    <SeverityBadge severity={alert.severity} />
                    <h3 className="font-bold text-sm text-gray-100">{alertTitle}</h3>
                    {alert.entity && (
                      <span className="text-xs text-green-400 font-sans font-medium">
                        [{alert.entity}]
                      </span>
                    )}
                  </div>

                  {/* Status Dropdown */}
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] text-gray-500 uppercase font-semibold">Status:</span>
                    <select
                      value={alert.status}
                      onChange={(e) => updateAlertStatus(alert.alertId, e.target.value)}
                      className="cyber-input text-[11px] font-mono py-1 px-2 bg-background"
                    >
                      <option value="new">New (Unreviewed)</option>
                      <option value="reviewed">Reviewed</option>
                      <option value="escalated">Escalated</option>
                      <option value="dismissed">Dismissed</option>
                    </select>
                  </div>
                </div>

                {/* Target Address & Basis */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs">
                  {alert.address && (
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500">Related Address:</span>
                      <AddressBadge
                        address={alert.address}
                        chain={chain}
                        onClick={(addr) => selectAddress(addr, 'address_intelligence')}
                        showFull
                      />
                    </div>
                  )}

                  <button
                    onClick={() => selectAddress(alert.address, 'address_intelligence')}
                    className="text-xs text-cyan-400 hover:underline flex items-center gap-1 font-sans self-end sm:self-auto"
                  >
                    Inspect Address Intel <ArrowRight className="w-3 h-3" />
                  </button>
                </div>

                {/* Underlying Evidence Summary */}
                {Array.isArray(alert.evidence) && alert.evidence.length > 0 && (
                  <div className="p-2.5 rounded bg-black/40 border border-panel-border/50 text-[11px] text-gray-400 font-mono">
                    Evidence links {alert.evidence.length} underlying transaction event(s) along this candidate flow.
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

