import React from 'react';
import { Compass, CheckCircle2, ArrowRight, ShieldCheck, FileCheck, ExternalLink, HelpCircle } from 'lucide-react';
import { useInvestigation } from '../../context/InvestigationContext';
import AddressBadge from '../common/AddressBadge';
import SeverityBadge from '../common/SeverityBadge';
import EmptyState from '../common/EmptyState';

export default function RecommendationsView() {
  const {
    traceData,
    selectAddress,
    setActiveSection,
  } = useInvestigation();

  const { recommendations = [], chain = 'ethereum' } = traceData || {};

  return (
    <div className="space-y-6 animate-fade-in">
      {/* ── Top Header ───────────────────────────────────────────────────── */}
      <div className="cyber-panel p-6 border-cyan-500/20 bg-gradient-to-r from-panel to-cyan-950/[0.08]">
        <div className="flex items-start gap-4">
          <div className="p-3 rounded-xl bg-cyan-500/10 text-cyan-400 shrink-0">
            <Compass className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs uppercase font-mono px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
                Decision Support
              </span>
              <span className="text-xs font-mono text-gray-400">
                Evidence-Driven Next Actions
              </span>
            </div>
            <h2 className="text-lg font-bold text-gray-100">Investigator Recommendations</h2>
            <p className="text-xs text-gray-400 mt-1 max-w-2xl leading-relaxed">
              Standard operating procedure guidance and evidentiary next steps generated by the recommendation engine based on verified graph findings.
            </p>
          </div>
        </div>

        <div className="mt-4 pt-3 border-t border-panel-border/50 text-[11px] text-gray-400 italic">
          Investigator assistance standard: Recommendations suggest evidentiary preservation and verification pathways; they do not draw legal conclusions or assert criminal culpability.
        </div>
      </div>

      {/* ── Recommendations List ─────────────────────────────────────────── */}
      {recommendations.length === 0 ? (
        <EmptyState
          title="No Action Items Required"
          subtitle="The investigated wallet flow exhibits no high-confidence suspicious attribution or compliance triggers."
          icon={CheckCircle2}
          type="neutral"
        />
      ) : (
        <div className="space-y-4">
          {recommendations.map((rec, idx) => {
            const priority = rec.priority || 'medium';

            return (
              <div
                key={idx}
                className="cyber-panel p-5 border-panel-border bg-black/20 space-y-3 hover:border-cyan-500/40 transition-colors"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-panel-border/50 pb-2.5">
                  <div className="flex items-center gap-2.5">
                    <span className="text-xs font-mono font-bold text-cyan-400">
                      REC-0{idx + 1}
                    </span>
                    <SeverityBadge severity={priority} />
                    <span className="text-xs uppercase font-mono text-gray-400 font-semibold">
                      Basis: {rec.basis || 'Graph Evidence'}
                    </span>
                  </div>

                  {rec.entity && (
                    <span className="text-xs font-medium text-green-400 bg-green-500/10 px-2 py-0.5 rounded border border-green-500/30">
                      Entity: {rec.entity}
                    </span>
                  )}
                </div>

                {/* Recommended Next Action */}
                <div className="space-y-1">
                  <span className="text-[10px] uppercase text-gray-500 font-semibold block tracking-wider">
                    Recommended Next Action
                  </span>
                  <p className="text-sm font-semibold text-gray-100 leading-snug">
                    {rec.action}
                  </p>
                </div>

                {/* Navigation Shortcut based on action */}
                <div className="pt-2 border-t border-panel-border/40 flex items-center justify-between">
                  <span className="text-[11px] text-gray-400">
                    Audit trail basis logged in evidence package
                  </span>

                  <div className="flex items-center gap-2">
                    {rec.action.toLowerCase().includes('candidate') && (
                      <button
                        onClick={() => setActiveSection('attribution')}
                        className="cyber-button-secondary text-xs py-1.5 px-3 flex items-center gap-1"
                      >
                        Open Attribution <ArrowRight className="w-3 h-3" />
                      </button>
                    )}
                    {rec.action.toLowerCase().includes('vasp') && (
                      <button
                        onClick={() => setActiveSection('vasp_intelligence')}
                        className="cyber-button-secondary text-xs py-1.5 px-3 flex items-center gap-1"
                      >
                        Open VASP Intel <ArrowRight className="w-3 h-3" />
                      </button>
                    )}
                    {rec.action.toLowerCase().includes('preserve') && (
                      <button
                        onClick={() => setActiveSection('evidence_integrity')}
                        className="cyber-button-primary text-xs py-1.5 px-3 flex items-center gap-1"
                      >
                        Preserve Evidence (SHA-256) <ArrowRight className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

